default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  # password: admin
  # password: 1234
  port: 54321
  password: abodyalex1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe_app

test:
  <<: *default
  database: Recipe_app_test

production:
  <<: *default
  database: Recipe_app_production
  username: Recipe_app
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
